#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 28 22:13:25 2021

@author: benlewis
"""

print("Hello World")

message = "Welcome to life!"

print(message)

message = "REM Rules"

print(message)

